name=DIYables TFT Shield Mega
version=1.0.2
author=DIYables.io
maintainer=DIYables.io (diyables.io@gmail.com)
sentence=The Arduino library for the DIYables 320x480, 3.5-inch Color TFT LCD Display Shield for Mega (16-bit parallel, Non-Touch). Compatible with Arduino Mega, Due, Giga and other Mega form factor boards.
paragraph=This library is designed for use with the 3.5-inch Color TFT LCD Display Shield (16-bit parallel interface) on Arduino Mega form factor boards such as Mega 2560, Due, Giga R1 WiFi, and other compatible models.
category=Display
url=http://diyables.io/tft-shield-mega
architectures=*
depends=Adafruit GFX Library
